### ISSUE TITLE
Update Ubuntu tag in Dockerfile

### ISSUE THREAD

**Issue by bschonec** [deanwilson/unixdaemon-dockerfiles#2]
That version of Ubuntu won't update when building the container from scratch.

**Comment by deanwilson** [comment]
Hi @bschonec, can you provide some more context please? Which line of which Dockerfile is the issue in?

**Comment by bschonec** [comment]
docker build fails when trying to build the container from ubuntu:14.10 image.  Updating FROM to something newer than ubuntu:14.10 fixed it for me.

`[root@puppet-server puppet-lint]# docker build -t foobar .
Sending build context to Docker daemon  5.12 kB
Step 1/10 : FROM ubuntu:14.10
 ---> a8a2ba3ce1a3
Step 2/10 : MAINTAINER Dean Wilson
 ---> Using cache
 ---> 2db84d171159
Step 3/10 : ENV REFRESHED_AT 2015-02-04-19-45-02
 ---> Using cache
 ---> 8336df2e9484
Step 4/10 : RUN apt-get -yqq update ; apt-get -yqq install ruby ca-certificates
 ---> Running in b43699809031

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 91.189.88.162 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found [IP: 91.189.88.162 80]
<snip>
E: Some index files failed to download. They have been ignored, or old ones used instead.
WARNING: The following packages cannot be authenticated!
  libyaml-0-2 openssl ca-certificates libjs-jquery rubygems-integration
  libruby2.1 ruby2.1 ruby
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get -yqq update ; apt-get -yqq install ruby ca-certificates' returned a non-zero code: 100
[root@puppet-server puppet-lint]# 
`

**Comment by deanwilson** [comment]
Resolved in #3 - thank you for raising it.
